apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: test-namespace
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  clusterIP: None